### ISSUE TITLE
Define USE_TUNING missing?

### ISSUE THREAD

**Issue by tillchess** [kmar/cheng4#1]
In most make_xxx.sh scripts you don't define -DUSE_TUNING , just in the Win version.

Is it recommended to include the define -DUSE_TUNING ?

**Comment by kmar** [comment]
USE_TUNING is internal preprocessor macro that should never be used for release builds
none of the build scripts uses -DUSE_TUNING, where do you see it?

**Comment by tillchess** [comment]
In the Visual Studio project

**Comment by kmar** [comment]
ah yes, don't use that :) I'm closing this now
